const fs=require("fs"),path=require("path"),ts=require("typescript"),Module=require("module");
const cache=new Map();function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file);let src=fs.readFileSync(file,"utf8"),js=ts.transpileModule(src,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,m=new Module(file,module);cache.set(file,m.exports);m.filename=file;m.paths=module.paths;m.require=function(id){if(id.startsWith(".")){let q=path.resolve(path.dirname(file),id);if(!path.extname(q))q+=".ts";if(fs.existsSync(q))return load(q)}return Module.prototype.require.call(m,id)};m._compile(js,file);cache.set(file,m.exports);return m.exports}
const p=load(path.join(__dirname,"../lib/engine/paths-v1.ts")),ch=load(path.join(__dirname,"../lib/engine/scenario-lab-v1.ts")),b=load(path.join(__dirname,"../lib/engine/choice-paths-boundary.ts")),ib=load(path.join(__dirname,"../lib/engine/path-input-boundary.ts")),rs=load(path.join(__dirname,"../lib/reference-data/schema.ts"));
let blocked=false;try{p.buildPathsView({intent:{action:"UNDERSTAND_PATHS"}})}catch(e){blocked=String(e).includes("PATHS_ENTRY_NOT_AUTHORIZED")}if(!blocked)throw Error("01 forged Paths intent accepted");
let fakeChoice=false;try{b.emitChoicePathsIntent({headline:"O próximo passo é seu.",actions:["UNDERSTAND_PATHS"]})}catch(e){fakeChoice=String(e).includes("CHOICE_STATE_NOT_AUTHORIZED")}if(!fakeChoice)throw Error("02 forged ChoiceState accepted");
const choice=ch.buildChoiceState("PATHS"),intent=b.emitChoicePathsIntent(choice),v=p.buildPathsView({intent});
if(v.cards.map(x=>x.pathId).join(",")!=="ACCUMULATION,FINANCING,CONSORTIUM")throw Error("03 taxonomy order");
if(v.focusedPath!==null||v.cards.some(x=>x.expanded))throw Error("04 default selection");
if(v.cards.some(x=>x.action!=="INSPECT_OR_SIMULATE"))throw Error("05 asymmetric action");
if(v.cards.map(x=>Object.keys(x).sort().join(",")).some((x,_,a)=>x!==a[0]))throw Error("06 asymmetric slots");
const fin={kind:"VEHICLE_FINANCING_AVERAGE_RATE",value:1.9,unit:"PERCENT_PER_MONTH",lineage:{source:"BCB",referenceId:"SGS25471",referencePeriod:"2026-08",retrievedAt:"2026-09-20T00:00:00Z",methodology:"official"}};
const finAuth=rs.authorizeValidatedVehiclePathReference(fin);
const missing=p.buildPathsView({intent,financing:{vehicleReferenceValue:100000,rateReference:finAuth}});
if(missing.cards[1].publicationStatus!=="INPUT_REQUIRED")throw Error("07 inferred financing inputs");
const av=p.buildPathsView({intent,accumulation:{currentResources:10000,monthlyContribution:1000,projectHorizonMonths:12}});
if(av.cards[0].publicationStatus!=="AUTHORIZED")throw Error("08 no-yield accumulation blocked");
if(av.cards[1].publicationStatus!=="INPUT_REQUIRED"||av.cards[2].publicationStatus!=="INPUT_REQUIRED")throw Error("09 isolation");
const down=ib.recordExplicitPathInput(intent,"FINANCING","allocatedDownPayment",20000),term=ib.recordExplicitPathInput(intent,"FINANCING","productTermMonths",48);
const goodFin=p.buildPathsView({intent,financing:{vehicleReferenceValue:100000,allocatedDownPayment:down,productTermMonths:term,rateReference:finAuth}});
if(goodFin.cards[1].publicationStatus!=="AUTHORIZED")throw Error("10 financing blocked");
if(goodFin.cards.map(x=>Object.keys(x).sort().join(",")).some((x,_,a)=>x!==a[0]))throw Error("11 mixed slots");
if(goodFin.cards[0].publication!==null||goodFin.cards[2].publication!==null)throw Error("12 null publication");
if(goodFin.cards.some((x,i)=>x.pathId!==["ACCUMULATION","FINANCING","CONSORTIUM"][i]))throw Error("13 availability reordered");
if(goodFin.cards.some(x=>x.expanded)||goodFin.focusedPath!==null)throw Error("14 availability selected");
const named=b.emitChoicePathsIntent(choice,"FINANCING");if(named.requestedPath!=="FINANCING")throw Error("15 named path lost");
let wrongPrimary=false;try{b.emitChoicePathsIntent(ch.buildChoiceState("CONTACT"))}catch(e){wrongPrimary=String(e).includes("CHOICE_PATHS_NOT_SELECTED")}if(!wrongPrimary)throw Error("16 unrelated primary action authorized");
if(p.captureExplicitUserAction||p.captureUserValue||p.captureSystemReference||p.authorizePathsEntryFromUserAction)throw Error("17 obsolete minting API exported");
if(!ch.isAuthorizedChoiceState(choice)||ch.isAuthorizedChoiceState({headline:"O próximo passo é seu.",actions:["UNDERSTAND_PATHS"]}))throw Error("18 ChoiceState authority broken");
let forgedInput=false;try{p.buildPathsView({intent,financing:{vehicleReferenceValue:100000,allocatedDownPayment:{pathId:"FINANCING",field:"allocatedDownPayment",value:20000},productTermMonths:term,rateReference:finAuth}})}catch(e){forgedInput=true}if(!forgedInput)throw Error("19 forged explicit input accepted");
let crossPath=false;try{p.buildPathsView({intent,financing:{vehicleReferenceValue:100000,allocatedDownPayment:ib.recordExplicitPathInput(intent,"CONSORTIUM","allocatedDownPayment",20000),productTermMonths:term,rateReference:finAuth}})}catch(e){crossPath=true}if(!crossPath)throw Error("20 cross-path input accepted");
let fakeSession=false;try{ib.recordExplicitPathInput({action:"UNDERSTAND_PATHS"},"FINANCING","productTermMonths",48)}catch(e){fakeSession=String(e).includes("PATH_INPUT_SESSION_NOT_AUTHORIZED")}if(!fakeSession)throw Error("20b forged path-input session accepted");
const forgedRef={value:fin};const badRef=p.buildPathsView({intent,financing:{vehicleReferenceValue:100000,allocatedDownPayment:down,productTermMonths:term,rateReference:forgedRef}});if(badRef.cards[1].publicationStatus!=="UNAVAILABLE")throw Error("21 forged reference accepted");
let invalidRef=false;try{rs.authorizeValidatedVehiclePathReference({...fin,lineage:{...fin.lineage,source:"B3"}})}catch(e){invalidRef=true}if(!invalidRef)throw Error("22 invalid reference authorized");
console.log("MWC-017J Paths mandatory boundary tests passed (22)");
