const fs=require("fs"),path=require("path"),ts=require("typescript"),Module=require("module");
const cache=new Map();function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file);let src=fs.readFileSync(file,"utf8"),js=ts.transpileModule(src,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,m=new Module(file,module);cache.set(file,m.exports);m.filename=file;m.paths=module.paths;m.require=function(id){if(id.startsWith(".")){let p=path.resolve(path.dirname(file),id);if(!path.extname(p))p+=".ts";if(fs.existsSync(p))return load(p)}return Module.prototype.require.call(m,id)};m._compile(js,file);cache.set(file,m.exports);return m.exports}
const p=load(path.join(__dirname,"../lib/engine/paths-v1.ts"));
let blocked=false;try{p.buildPathsView({authority:{origin:"CHOICE_UNDERSTAND_PATHS"}})}catch(e){blocked=String(e).includes("PATHS_ENTRY_NOT_AUTHORIZED")}if(!blocked)throw Error("01 forged authority accepted");\nconst ua=p.captureExplicitUserAction("UNDERSTAND_PATHS");const auth=p.authorizePathsEntryFromUserAction(ua);const v=p.buildPathsView({authority:auth});
if(v.cards.map(x=>x.pathId).join(",")!=="ACCUMULATION,FINANCING,CONSORTIUM")throw Error("02 taxonomy order changed");
if(v.focusedPath!==null||v.cards.some(x=>x.expanded))throw Error("03 default focus/expansion");
if(v.cards.some(x=>x.action!=="INSPECT_OR_SIMULATE"))throw Error("04 asymmetric action");
if(v.cards.map(x=>Object.keys(x).sort().join(",")).some((x,_,a)=>x!==a[0]))throw Error("05 asymmetric card slots");
let forgedAction=false;try{p.authorizePathsEntryFromUserAction({action:"UNDERSTAND_PATHS"})}catch(e){forgedAction=String(e).includes("USER_ACTION_NOT_AUTHORIZED")}if(!forgedAction)throw Error("06 forged user action accepted");
const fin={kind:"VEHICLE_FINANCING_AVERAGE_RATE",value:1.9,unit:"PERCENT_PER_MONTH",lineage:{source:"BCB",referenceId:"SGS25471",referencePeriod:"2026-08",retrievedAt:"2026-09-20T00:00:00Z",methodology:"official"}};
const fv=p.buildPathsView({authority:auth,financing:{vehicleReferenceValue:p.captureUserValue(100000),rateReference:p.captureSystemReference(fin)}});
if(fv.cards[1].publicationStatus!=="INPUT_REQUIRED")throw Error("07 financing inferred missing inputs");
if(fv.cards[0].pathId!=="ACCUMULATION"||fv.cards[2].pathId!=="CONSORTIUM")throw Error("08 unavailable/input-required reordered paths");
const av=p.buildPathsView({authority:auth,accumulation:{currentResources:p.captureUserValue(10000),monthlyContribution:p.captureUserValue(1000),projectHorizonMonths:p.captureUserValue(12)}});
if(av.cards[0].publicationStatus!=="AUTHORIZED")throw Error("09 no-yield accumulation blocked");
if(av.cards[1].publicationStatus!=="INPUT_REQUIRED"||av.cards[2].publicationStatus!=="INPUT_REQUIRED")throw Error("10 failure isolation broken");
let fakeUser=false;try{p.buildPathsView({authority:auth,accumulation:{currentResources:{value:10000,provenance:"USER_ENTERED"},monthlyContribution:p.captureUserValue(1000),projectHorizonMonths:p.captureUserValue(12)}})}catch(e){fakeUser=true}if(!fakeUser&&p.buildPathsView({authority:auth,accumulation:{currentResources:{value:10000,provenance:"USER_ENTERED"},monthlyContribution:p.captureUserValue(1000),projectHorizonMonths:p.captureUserValue(12)}}).cards[0].publicationStatus!=="UNAVAILABLE")throw Error("11 forged USER_ENTERED accepted");
const badRef=p.buildPathsView({authority:auth,financing:{vehicleReferenceValue:p.captureUserValue(100000),allocatedDownPayment:p.captureUserValue(20000),productTermMonths:p.captureUserValue(48),rateReference:{value:fin,provenance:"SYSTEM_REFERENCE"}}});if(badRef.cards[1].publicationStatus!=="UNAVAILABLE")throw Error("12 forged SYSTEM_REFERENCE accepted");
const goodFin=p.buildPathsView({authority:auth,financing:{vehicleReferenceValue:p.captureUserValue(100000),allocatedDownPayment:p.captureUserValue(20000),productTermMonths:p.captureUserValue(48),rateReference:p.captureSystemReference(fin)}});if(goodFin.cards[1].publicationStatus!=="AUTHORIZED")throw Error("13 authorized financing blocked");
if(goodFin.cards.map(x=>Object.keys(x).sort().join(",")).some((x,_,a)=>x!==a[0]))throw Error("14 mixed-state card slots asymmetric");
if(goodFin.cards[0].publication!==null||goodFin.cards[2].publication!==null)throw Error("15 empty publication slot not null");
const namedAction=p.captureExplicitUserAction("UNDERSTAND_PATHS","FINANCING"),namedAuth=p.authorizePathsEntryFromUserAction(namedAction);if(namedAuth.requestedPath!=="FINANCING")throw Error("16 named path authority lost");
if(goodFin.cards.some((x,i)=>x.pathId!==["ACCUMULATION","FINANCING","CONSORTIUM"][i]))throw Error("17 taxonomy order changed by availability");
if(goodFin.cards.some(x=>x.expanded)||goodFin.focusedPath!==null)throw Error("18 availability caused selection");
console.log("MWC-017 Paths V1 direct boundary tests passed (18)");
