import type { ConsortiumAdminFeeReference, DiRateReference, VehicleFinancingRateReference } from "../reference-data/types";
import { validateVehiclePathReference } from "../reference-data/schema";
import { calculateAccumulation, calculateConsortiumReference, calculateFinancing } from "../project/vehicle/path-engine";
export const CALCULATION_EVIDENCE=Symbol("MWC_CALCULATION_EVIDENCE");
export type CalculationEvidence<I,R,Ref=undefined>=Readonly<{[CALCULATION_EVIDENCE]:true;input:Readonly<I>;reference:Readonly<Ref>|undefined;result:Readonly<R>}>;
function freeze<T>(x:T):Readonly<T>{return Object.freeze({...x}) as Readonly<T>}
function evidence<I,R,Ref=undefined>(input:I,result:R,reference?:Ref):CalculationEvidence<I,R,Ref>{return Object.freeze({[CALCULATION_EVIDENCE]:true,input:freeze(input),reference:reference?freeze(reference):undefined,result:freeze(result)}) as CalculationEvidence<I,R,Ref>}
function validateRef<T>(ref:T,kind:string):T{const r=validateVehiclePathReference(ref as never);if(!r.ok||r.value.kind!==kind)throw new RangeError("INVALID_REFERENCE_KIND");return r.value as T}
export type AccumulationEvidence=CalculationEvidence<{currentResources:number;monthlyContribution:number;projectHorizonMonths:number},{withoutYield:number;withDiReference:number|null},DiRateReference>;
export type FinancingEvidence=CalculationEvidence<{vehicleReferenceValue:number;allocatedDownPayment:number;productTermMonths:number},{principal:number;payment:number;installmentsTotal:number;projectedOutlay:number;mathematicalInterest:number;productTermMonths:number},VehicleFinancingRateReference>;
export type ConsortiumEvidence=CalculationEvidence<{creditReference:number;productTermMonths:number},{administrationReference:number;baseSimulatedTotal:number;baseMathematicalInstallment:number;productTermMonths:number},ConsortiumAdminFeeReference>;
export function calculateAccumulationForFacts(input:{currentResources:number;monthlyContribution:number;projectHorizonMonths:number;diReference?:DiRateReference}):AccumulationEvidence{const ref=input.diReference?validateRef(input.diReference,"DI_RATE"):undefined;const canonical={currentResources:input.currentResources,monthlyContribution:input.monthlyContribution,projectHorizonMonths:input.projectHorizonMonths};return evidence(canonical,calculateAccumulation({...canonical,diReference:ref}),ref)}
export function calculateFinancingForFacts(input:{vehicleReferenceValue:number;allocatedDownPayment:number;productTermMonths:number;rateReference:VehicleFinancingRateReference}):FinancingEvidence{const ref=validateRef(input.rateReference,"VEHICLE_FINANCING_AVERAGE_RATE");const canonical={vehicleReferenceValue:input.vehicleReferenceValue,allocatedDownPayment:input.allocatedDownPayment,productTermMonths:input.productTermMonths};return evidence(canonical,calculateFinancing({vehicleReferenceValue:canonical.vehicleReferenceValue,downPayment:canonical.allocatedDownPayment,productTermMonths:canonical.productTermMonths,rateReference:ref}),ref)}
export function calculateConsortiumForFacts(input:{creditReference:number;productTermMonths:number;adminFeeReference:ConsortiumAdminFeeReference}):ConsortiumEvidence{const ref=validateRef(input.adminFeeReference,"CONSORTIUM_ADMIN_FEE_AVERAGE");const canonical={creditReference:input.creditReference,productTermMonths:input.productTermMonths};return evidence(canonical,calculateConsortiumReference({...canonical,adminFeeReference:ref}),ref)}
export function assertCalculationEvidence<I,R,Ref>(value:CalculationEvidence<I,R,Ref>):void{if(!value||value[CALCULATION_EVIDENCE]!==true||!Object.isFrozen(value)||!Object.isFrozen(value.input)||!Object.isFrozen(value.result)||(value.reference!==undefined&&!Object.isFrozen(value.reference)))throw new RangeError("CALCULATION_EVIDENCE_REQUIRED")}
