import type { Fact, RequiredDisclosure, SemanticId } from "./fact-engine-v2";
import { isAuthorizedClaim,isClaimCompatible,type AuthorizedClaim } from "./claim-registry-v2";
export type PublicationSurface="CARD"|"COMPARISON"|"REPORT"|"NARRATIVE"; export type DisclosureScope="FACT"|"CLAIM"|"CARD"|"PUBLICATION";
export type DisclosureBinding=Readonly<{disclosureId:RequiredDisclosure;scope:DisclosureScope;coversFactIds:readonly string[];coversClaimIds:readonly string[]}>;
export type ClaimRealization=Readonly<{claimId:string;text:string;factId:string;renderedValue?:string;label?:string;unit?:Fact["value"]["unit"]}>;
export type PublicationCandidate=Readonly<{publicationId:string;surface:PublicationSurface;claims:readonly AuthorizedClaim[];realizations:readonly ClaimRealization[];disclosureBindings:readonly DisclosureBinding[]}>;
export type OutputFailure="FACT_UNAVAILABLE"|"FACT_INVALID"|"FACT_NOT_AUTHORIZED"|"CLAIM_NOT_REGISTERED"|"CLAIM_FACT_MISMATCH"|"UNSUPPORTED_CLAIM"|"VALUE_MISMATCH"|"UNIT_MISMATCH"|"LABEL_MISMATCH"|"SEMANTIC_MISMATCH"|"REQUIRED_DISCLOSURE_MISSING"|"DISCLOSURE_BINDING_MISSING"|"DISCLOSURE_SCOPE_INVALID"|"INCOMPLETE_FACT_PRESENTED_AS_COMPLETE"|"COMPARISON_NOT_AUTHORIZED"|"COMPARISON_CONTEXT_MISSING"|"UNSTRUCTURED_COMPARISON"|"UNKNOWN_PRESENTED_AS_ZERO"|"DATED_PRESENTED_AS_CURRENT"|"PRODUCT_TERM_INFERRED"|"RESOURCE_ALLOCATION_INFERRED"|"RECOMMENDATION_DETECTED"|"RANKING_DETECTED"|"SUITABILITY_INFERENCE_DETECTED"|"PRESENTATION_ASYMMETRY"|"PUBLICATION_MUTATED_AFTER_VALIDATION"|"AI_OUTPUT_VALIDATION_FAILURE";
export type ValidationResult={ok:true;publication:AuthorizedPublication}|{ok:false;reason:OutputFailure}; export type AuthorizedPublication=Readonly<{publicationId:string;payload:PublicationCandidate;validationDigest:string}>;
const labels:Partial<Record<SemanticId,readonly string[]>>={FINANCING_MATHEMATICAL_PRICE_INSTALLMENT:["Parcela matemática","Parcela matemática Price"],FINANCING_PROJECTED_OUTLAY:["Desembolso projetado"],CONSORTIUM_BASE_SIMULATED_TOTAL:["Base matemática simulada"],CONSORTIUM_BASE_MATHEMATICAL_INSTALLMENT:["Parcela matemática base"],FINANCING_AVERAGE_MONTHLY_RATE:["Taxa média de referência"],ACCUMULATION_GROSS_DI_REFERENCE_PROJECTION:["Projeção bruta de referência DI"]};
const recommendation=/\b(melhor|pior|recomendad[oa]|ideal|vantajos[oa]|mais\s+adequad[oa]|faz\s+mais\s+sentido|se\s+destaca|mais\s+atrativ[oa]|mais\s+eficiente)\b/i, comparative=/\b(maior|menor|mais|menos|barat[oa]|car[oa]|rápid[oa]|lent[oa]|econ[oô]mic[oa]|eficiente|atrativ[oa]|vantajos[oa]|melhor|pior)\b/i,totality=/\b(custo\s+total|valor\s+final|tudo\s+que\s+(?:você\s+)?pag|custo\s+completo|desembolso\s+definitivo)\b/i,current=/\b(atual|hoje|vigente|taxa\s+atual)\b/i,zero=/\b(?:r\$\s*)?0(?:[,.]00)?\b/i;
function cloneFreeze<T>(v:T):T{if(v&&typeof v==="object"){const o:any=Array.isArray(v)?[...(v as any)]:{...(v as any)};for(const k of Object.keys(o))o[k]=cloneFreeze(o[k]);return Object.freeze(o)}return v}
function digest(c:PublicationCandidate){const s=JSON.stringify(c);let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,"0")}
function binding(c:PublicationCandidate,f:Fact,cl:AuthorizedClaim,d:RequiredDisclosure):OutputFailure|undefined{const matches=c.disclosureBindings.filter(b=>b.disclosureId===d&&(b.coversFactIds.includes(f.id)||b.coversClaimIds.includes(cl.claimId)));if(!matches.length)return"DISCLOSURE_BINDING_MISSING";if(matches.some(b=>(b.scope==="FACT"&&b.coversFactIds.includes(f.id))||(b.scope==="CLAIM"&&b.coversClaimIds.includes(cl.claimId))||((b.scope==="CARD"||b.scope==="PUBLICATION")&&(b.coversFactIds.includes(f.id)||b.coversClaimIds.includes(cl.claimId)))))return;return"DISCLOSURE_SCOPE_INVALID"}
export function validatePublication(facts:readonly Fact[],c:PublicationCandidate):ValidationResult{const bf=new Map(facts.map(f=>[f.id,f])),bc=new Map(c.claims.map(x=>[x.claimId,x]));
 for(const cl of c.claims){if(!isAuthorizedClaim(cl))return{ok:false,reason:"CLAIM_NOT_REGISTERED"};const sf=cl.subjectFactIds.map(id=>bf.get(id)).filter(Boolean) as Fact[];if(sf.length!==cl.subjectFactIds.length||!isClaimCompatible(cl,sf))return{ok:false,reason:"SEMANTIC_MISMATCH"};if(cl.claimType==="COMPARISON_CLAIM"){const x=cl.comparison;if(!x)return{ok:false,reason:"COMPARISON_CONTEXT_MISSING"};const l=bf.get(x.leftFactId),r=bf.get(x.rightFactId);if(!l||!r||x.exactLeftValue!==l.value.exactValue||x.exactRightValue!==r.value.exactValue||x.unit!==l.value.unit||x.unit!==r.value.unit)return{ok:false,reason:"COMPARISON_NOT_AUTHORIZED"}}}
 for(const r of c.realizations){const cl=bc.get(r.claimId);if(!cl||!isAuthorizedClaim(cl))return{ok:false,reason:"CLAIM_NOT_REGISTERED"};const f=bf.get(r.factId);if(!f||!cl.subjectFactIds.includes(f.id))return{ok:false,reason:"CLAIM_FACT_MISMATCH"};if(f.state.availability!=="AVAILABLE")return{ok:false,reason:"FACT_UNAVAILABLE"};if(f.state.validation!=="VALIDATED")return{ok:false,reason:"FACT_INVALID"};if(f.state.authorization==="NOT_AUTHORIZED")return{ok:false,reason:"FACT_NOT_AUTHORIZED"};
  if(r.renderedValue!==undefined&&!new Set([String(f.value.exactValue),f.value.displayValue]).has(r.renderedValue))return{ok:false,reason:"VALUE_MISMATCH"};if(r.unit!==undefined&&r.unit!==f.value.unit)return{ok:false,reason:"UNIT_MISMATCH"};
  if(r.label!==undefined){const a=labels[f.semanticId];if(a&&!a.includes(r.label))return{ok:false,reason:"LABEL_MISMATCH"}}
  for(const d of new Set([...f.requiredDisclosures,...cl.requiredDisclosures])){const e=binding(c,f,cl,d);if(e)return{ok:false,reason:e}}
  const full=`${r.label??""} ${r.text}`;if(f.state.completeness==="PARTIAL"&&totality.test(full))return{ok:false,reason:"INCOMPLETE_FACT_PRESENTED_AS_COMPLETE"};if(f.state.freshness!=="CURRENT"&&current.test(full))return{ok:false,reason:"DATED_PRESENTED_AS_CURRENT"};if((f.state.availability!=="AVAILABLE"||f.state.completeness==="UNKNOWN")&&zero.test(full))return{ok:false,reason:"UNKNOWN_PRESENTED_AS_ZERO"};if(recommendation.test(full))return{ok:false,reason:"RECOMMENDATION_DETECTED"};if(comparative.test(full)&&cl.claimType!=="COMPARISON_CLAIM")return{ok:false,reason:"UNSTRUCTURED_COMPARISON"}}
 const frozen=cloneFreeze(c);return{ok:true,publication:Object.freeze({publicationId:c.publicationId,payload:frozen,validationDigest:digest(frozen)})}}
