export const EDITORIAL_HYPOTHESES = Object.freeze({ navigationLabel: "Explore", masthead: "Antes da Escolha", landingPath: "/descobrir" });
export type EditorialClaimClass = "EVERGREEN_EXPLANATION" | "CURRENT_REFERENCE" | "MODELED_EXAMPLE" | "PRODUCT_SPECIFIC" | "EDITORIAL_OPINION";
export type EditorialArticle = Readonly<{ id:string; slug:string; topicId:string; headline:string; deck:string; publishedAt:string; readingTimeEstimate?:string; claimClasses:readonly EditorialClaimClass[]; sourceNotes?:readonly string[]; assumptions?:readonly string[]; relatedArticleIds:readonly string[]; sections:readonly Readonly<{heading:string; paragraphs:readonly string[]}>[] }>;
export const EDITORIAL_ARTICLES: readonly EditorialArticle[] = Object.freeze([
{id:"financiamento-projeto-inteiro",slug:"financiamento-projeto-inteiro",topicId:"editorial:financiamento",headline:"Financiamento parece caber no mês. Mas quanto ele representa no projeto inteiro?",deck:"A parcela é só uma parte da leitura. Prazo, valor financiado e custo total mudam a perspectiva.",publishedAt:"2026-09-20",readingTimeEstimate:"5 min",claimClasses:["EVERGREEN_EXPLANATION"],relatedArticleIds:["preco-mesmo-caminho-diferente"],sections:[{heading:"A parcela responde só uma pergunta",paragraphs:["Saber se uma prestação cabe no orçamento é importante, mas isso não descreve sozinho o compromisso inteiro.","Antes de comparar alternativas, vale separar valor do bem, recursos destinados à entrada, valor efetivamente financiado, prazo e condições da operação."]},{heading:"Olhar o projeto inteiro",paragraphs:["Uma comparação útil pode começar tornando visíveis as variáveis que mudam de um cenário para outro.","A decisão continua sendo sua. O papel da informação é deixar as diferenças mais compreensíveis."]}]},
{id:"consorcio-juros",slug:"consorcio-tem-juros",topicId:"editorial:consorcio",headline:"Consórcio tem juros? A resposta curta não conta a história toda.",deck:"Uma pergunta simples pode esconder componentes diferentes. Entender os nomes evita comparar coisas que não são equivalentes.",publishedAt:"2026-09-20",readingTimeEstimate:"4 min",claimClasses:["EVERGREEN_EXPLANATION"],relatedArticleIds:["preco-mesmo-caminho-diferente"],sections:[{heading:"Comece pelos componentes",paragraphs:["Em vez de reduzir a análise a uma única palavra, é mais útil identificar quais componentes podem existir e quais condições pertencem ao contrato específico.","Taxa de administração, eventuais fundos, seguros, regras de atualização e demais condições não devem ser tratados como se fossem a mesma coisa."]},{heading:"Perguntas melhores ajudam mais",paragraphs:["Ao conhecer os componentes, você consegue ler propostas e documentos com perguntas mais específicas. Isso melhora a comparação sem transformar informação em recomendação."]}]},
{id:"recursos-agora-ou-depois",slug:"recursos-agora-ou-depois",topicId:"editorial:planejamento",headline:"Você tem R$ 20 mil para o carro. Usar agora ou continuar juntando?",deck:"O número sozinho não decide. O que muda quando recursos, tempo e objetivo entram na mesma conversa?",publishedAt:"2026-09-20",readingTimeEstimate:"5 min",claimClasses:["MODELED_EXAMPLE"],assumptions:["R$ 20 mil é apenas um exemplo ilustrativo, não uma recomendação nem valor de referência de mercado."],relatedArticleIds:["preco-mesmo-caminho-diferente"],sections:[{heading:"Um valor pode cumprir papéis diferentes",paragraphs:["Imagine, apenas como exemplo, que uma pessoa separou R$ 20 mil para um projeto de veículo.","A pergunta útil não é qual opção é universalmente melhor, mas quais variáveis mudam em cada cenário: tempo, recursos preservados, compromisso mensal e condições da solução considerada."]}]},
{id:"preco-mesmo-caminho-diferente",slug:"preco-mesmo-caminho-diferente",topicId:"editorial:decisoes",headline:"O preço é o mesmo. O caminho até ele pode não ser.",deck:"Duas pessoas podem olhar para o mesmo objetivo e organizar trajetórias completamente diferentes.",publishedAt:"2026-09-20",readingTimeEstimate:"4 min",claimClasses:["EVERGREEN_EXPLANATION"],relatedArticleIds:["financiamento-projeto-inteiro","consorcio-juros"],sections:[{heading:"Preço e caminho são coisas diferentes",paragraphs:["O valor de um objetivo descreve o destino financeiro do projeto. Ele não determina automaticamente como a pessoa deve chegar até lá.","Prazo desejado, recursos disponíveis e condições das soluções consideradas mudam a estrutura do planejamento."]}]}
]);
export function getEditorialArticle(slug:string){return EDITORIAL_ARTICLES.find(a=>a.slug===slug)}
export function getRelatedArticles(article:EditorialArticle){return article.relatedArticleIds.map(id=>EDITORIAL_ARTICLES.find(a=>a.id===id)).filter((a):a is EditorialArticle=>Boolean(a))}
export function validateEditorialRegistry(){for(const a of EDITORIAL_ARTICLES){if(!a.topicId.startsWith("editorial:"))throw new Error("EDITORIAL_TOPIC_NAMESPACE_REQUIRED");if(a.claimClasses.includes("CURRENT_REFERENCE")&&(!a.sourceNotes||!a.sourceNotes.length))throw new Error("CURRENT_REFERENCE_PROVENANCE_REQUIRED");if(a.claimClasses.includes("MODELED_EXAMPLE")&&(!a.assumptions||!a.assumptions.length))throw new Error("MODELED_EXAMPLE_ASSUMPTIONS_REQUIRED")}return true}
